AppName: moment-svc
PprofPort: :5557

HTTP:
  Addr: :8082
  ReadTimeout: 3s
  WriteTimeout: 3s
  Mode: debug                 # debug, release, test
  JwtSecret: JWT_SECRET
  JwtTimeout: 86400
  CookieName: jwt-token
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  EnableTrace: false
  EnablePprof: true

GRPC:
  Addr: :9092
  ReadTimeoutSecond: 5
  WriteTimeoutSecond: 5

Redis:
  Addr: 127.0.0.1:6379

UserDatabase:
  Host: 127.0.0.1
  UserName: root
  Password: 123
  Database: user
  Max: 123
  Min: 12

Log:
