Name: moment-svc
Version: 1.0.0
PprofPort: :5557

HTTP:
  Addr: :8082
  ReadTimeout: 3s
  WriteTimeout: 3s
  Mode: debug                 # debug, release, test
  JwtSecret: JWT_SECRET
  JwtTimeout: 86400
  CookieName: jwt-token
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  EnableTrace: false
  EnablePprof: true
GRPC:
  Addr: :9092
  ReadTimeout: 5s
  WriteTimeout: 5s


Redis:
